"""initial migration

Revision ID: a51dd48d221c
Revises: 6b674e683988
Create Date: 2017-12-31 10:38:39.634121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51dd48d221c'
down_revision = '6b674e683988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grouptype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grouptype_group'), 'grouptype', ['group'], unique=False)
    op.create_table('meetingtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetingtype_meeting'), 'meetingtype', ['meeting'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetingtype_meeting'), table_name='meetingtype')
    op.drop_table('meetingtype')
    op.drop_index(op.f('ix_grouptype_group'), table_name='grouptype')
    op.drop_table('grouptype')
    # ### end Alembic commands ###
